name: Pull Request
description: Submit a contribution to unifi-docker
title: "Short description of your change"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to **unifi-docker**! 💚  
        This form helps provide just enough context for maintainers to review your PR quickly.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe what this pull request changes.
      placeholder: |
        Example:
        - Update PKGURL to the latest UniFi Network Application version.
        - Adjust README current version table.
    validations:
      required: true

  - type: textarea
    id: related_issues
    attributes:
      label: Related issues
      description: |
        If this PR is connected to any issues, list them here.  
        You can use keywords like:
        - closes #123  
        - fixes #456
      placeholder: |
        closes #123
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: A quick self-check before submitting.
      options:
        - label: My changes build and run locally (where applicable).
        - label: I’ve reviewed Dockerfile/README changes for accuracy (if affected).
        - label: I’m open to feedback and ready to adjust this PR if needed.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thanks again for helping improve the project! 🙌
