name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: llinux/arm/v7,linux/arm64/v8,linux/amd64
          push: false
          tags: unifi:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
