name: Build Docker Image

on:
  push:
    branches:
      - master
  schedule:
    - cron: 23 3 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and upload the docker image
        env:
          DOCKER_HUB_REPO: tombull/unifi
        run: |
          echo ${{secrets.DOCKER_HUB_TOKEN}} | docker login --username tombull --password-stdin
          export SHORT_SHA=`git rev-parse --short=7 ${GITHUB_SHA}`
          docker build . --file Dockerfile --build-arg BUILD_VERSION=${SHORT_SHA} --tag ${DOCKER_HUB_REPO}:${SHORT_SHA} --tag ${DOCKER_HUB_REPO}:latest
          docker push ${DOCKER_HUB_REPO}:${SHORT_SHA}
          docker push ${DOCKER_HUB_REPO}:latest
      - name: Trigger deployment webhook
        env:
          DOCKER_HUB_REPO: tombull/unifi
        run: |
          export SHORT_SHA=`git rev-parse --short=7 ${GITHUB_SHA}`
          curl -X POST -H "Content-Type: application/json" --data "{ \"name\": \"${DOCKER_HUB_REPO}\", \"tag\": \"${SHORT_SHA}\" }" https://keel.iteralis.com/v1/webhooks/native
